# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
description:      ''
url:              https://jacob.moorman.me/hyde
baseurl:          ""

author:
  name:           'Jacob Moorman'
  url:            https://jacob.moorman.me/

# Blog configuration
has_blog:         True
paginate:         1
paginate_path:    "/blog/page:num/"
blog_url:        "/blog/"

# Configure prose
prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
